version: '3.8'
services:
  web:
    build:
      context: .
    image: api_img
    restart: always
    ports:
      - "8004:8000"
    volumes:
      - ./app:/usr/src/app
      - ~/.kube:/home/lle57/.kube      
    depends_on:
      - db
      #condition: service_healthy
      #restart: true
    env_file:
      - .env
      
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: microservices
      PYTHONPATH: /usr/src/app
      KUBECONFIG: /home/lle57/.kube/config
    entrypoint: ["/bin/bash", "-c", "/usr/src/app/wait_for_it.sh test_db"]

   
  db:
    image: postgres
    restart: always
    
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: microservices
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data 
    
 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8005:8080"
 
volumes:
  pgdata:

